   # I have included a build-run.sh in the git
   # 1. build-run.sh gets zipped up correctly
   # 2. the zip file uploads to AWS S3 correctly
   # 3. the .zip file dpeloys out to the EB.ec2
   # 4. BUT the build.sh file is missing on server /var/app/current/  ???WHY???
   # 5. --> alternative solution.. put .sh file in home,a nd run from there?
   #
   # these logs are saved on ec2 server: /var/log/cfn-init-cmd.log
   # sudo tail -n 50 -f /var/log/cfn-init-cmd.log
   #
files:
  "/home/ec2-user/build-run.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/bin/bash
      cd /var/app/current
      npm run build
      pm2 start api/dist/index.js
      exit 0;
commands:
    00_start_script:
        command: "WALL running 00_npm.config"
    01_install_htop:
        command: sudo yum -y install htop
    03_install_nmap:
        command: sudo yum -y install nmap
    04_install_pm2:
        command: sudo npm i -g pm2
    05_export_pm2_path:  
        export PATH=$PATH:/opt/elasticbeanstalk/node-install/node-v14.18.2-linux-x64/lib/node_modules/pm2/bin
    # adrian: i think this will cause a error.. so i commented out
    # 06_verify_pm2:
        # command: pm2 list
    10_check_path:
        command: pwd
    11_show_path:
        command: ls -lah
    15_echo_date:
        command: sudo date >> /home/ec2-user/date.txt
    16_talk_wall:
        command: "wall DEPLOYED and RUNNING: 00_npm.config - 11_talk_wall "
    20_build_run:
        command: "bash /home/ec2-user/build-run.sh"
    # 29_setup_run:
    #    command: "bash ./var/app/current/build-run.sh"
    # 30_setup_run:
    #     command: "bash .ebextensions/bin/setup.sh"

   #
   #
   # deploy errors
   #
   # /var/log/cfn-init.log
   # 2022-01-30 02:20:42,160 [ERROR] Error encountered during build of prebuild_0_demo_nft_sportscast_net: Command 11_setup_run failed
   #  Traceback (most recent call last):
   #  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
   #    CloudFormationCarpenter(config, self._auth_config).build(worklog)
   #  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
   #    self._config.commands)
   #  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
   #    raise ToolError(u"Command %s failed" % name)
   # cfnbootstrap.construction_errors.ToolError: Command 11_setup_run failed
   # 2022-01-29 23:08:27,764 [ERROR] Unhandled exception during build: Command 011_setup_run failed
   #
   # 30_setup_run:
   #     command: "setup.sh"
   #
   # 31_setup_run:
   #     command: "bash .ebextensions/setup.sh"